name: ESP32 Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install ESP-IDF and Build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4.1
        target: esp32

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: esp32-firmware
        path: |
          build/*.bin
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
        retention-days: 30

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: esp32-firmware
        path: build/

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/esp32_airzone.bin
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          ESP32 Airzone Firmware Release
          
          ## Changes
          - Automated build from commit ${{ github.sha }}
          
          ## Files
          - `esp32_airzone.bin`: Main application firmware
          - `bootloader.bin`: ESP32 bootloader
          - `partition-table.bin`: Partition table
          
          ## Installation
          Use ESP-IDF or esptool to flash these files to your ESP32 device.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 