name: ESP32 Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4.1
        target: esp32

    - name: Build project
      run: |
        idf.py build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: esp32-firmware
        path: |
          build/*.bin
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
        retention-days: 30

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4.1
        target: esp32

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: esp32-firmware
        path: build/

    - name: Run unit tests (if any)
      run: |
        # Add unit tests here when available
        echo "No unit tests configured yet"
        # idf.py test

    - name: Check code formatting
      run: |
        # Check if code follows ESP-IDF style guidelines
        idf.py check-format
        idf.py check-format --check

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: cpp

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4.1
        target: esp32

    - name: Build for CodeQL
      run: |
        idf.py build

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  release:
    runs-on: ubuntu-latest
    needs: [build, test, security]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: esp32-firmware
        path: build/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/esp32_airzone.bin
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          ESP32 Airzone Firmware Release
          
          ## Changes
          - Automated build from commit ${{ github.sha }}
          
          ## Files
          - `esp32_airzone.bin`: Main application firmware
          - `bootloader.bin`: ESP32 bootloader
          - `partition-table.bin`: Partition table
          
          ## Installation
          Use ESP-IDF or esptool to flash these files to your ESP32 device.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 